### ISSUE TITLE
Dato CMS client stuck at version 0.6.1

### ISSUE THREAD

**Issue by Siilwyn** [voorhoede/hike-one#333]
Upgrading causes the data dump to fail, see upstream issue:
https://github.com/datocms/js-datocms-client/issues/21

**Comment by vvandijck** [comment]
I updated the `datocms-client` package in #426. And the issue seems to be fixed 😄

**Comment by Siilwyn** [comment]
Resolved in upstream https://github.com/datocms/js-datocms-client/issues/21
